(G-CODE GENERATED BY FLATCAM v8.993 - www.flatcam.org - Version Date: 2020/06/05)

(Name: 1.2_hole)
(Type: G-code from Excellon)
(Units: MM)

(Created on Saturday, 10 January 2026 at 17:43)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 0.7)
(Tool: 2 -> Dia: 0.8)
(Tool: 3 -> Dia: 0.8)
(Tool: 4 -> Dia: 0.9)
(Tool: 5 -> Dia: 1.0)
(Tool: 6 -> Dia: 1.2)
(Tool: 7 -> Dia: 1.3)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)
(Tool: 3 -> Feedrate: 300)
(Tool: 4 -> Feedrate: 300)
(Tool: 5 -> Feedrate: 300)
(Tool: 6 -> Feedrate: 300)
(Tool: 7 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)
(Tool: 3 -> Feedrate Rapids: 1500)
(Tool: 4 -> Feedrate Rapids: 1500)
(Tool: 5 -> Feedrate Rapids: 1500)
(Tool: 6 -> Feedrate Rapids: 1500)
(Tool: 7 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.7)
(Tool: 2 -> Z_Cut: -1.7)
(Tool: 3 -> Z_Cut: -1.7)
(Tool: 4 -> Z_Cut: -1.7)
(Tool: 5 -> Z_Cut: -1.7)
(Tool: 6 -> Z_Cut: -1.7)
(Tool: 7 -> Z_Cut: -1.7)

(Tools Offset: )
(Tool: 6 -> Offset Z: -0.0)
(Tool: 7 -> Offset Z: -0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)
(Tool: 3 -> Z_Move: 2)
(Tool: 4 -> Z_Move: 2)
(Tool: 5 -> Z_Move: 2)
(Tool: 6 -> Z_Move: 2)
(Tool: 7 -> Z_Move: 2)

(Z Start: None mm)
(Z End: 2.0 mm)
(Steps per circle: 64)
(Preprocessor Excellon: grbl_11)

(X range:    4.6000 ...   73.5050  mm)
(Y range:   11.6380 ...   71.8580  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G17
G94




G00 Z2.0000

G01 F300.00
M03 S10000
G00 X34.9500 Y32.7910
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X31.4500 Y32.7910
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G01 F300.00
M03 S10000
G00 X58.5570 Y49.6350
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X53.5570 Y49.6350
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X32.4570 Y58.2560
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X22.4570 Y60.7560
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X32.4570 Y63.2560
G01 Z-1.7000
G01 Z0
G00 Z2.0000
G00 X56.0570 Y59.6350
G01 Z-1.7000
G01 Z0
G00 Z2.0000
M05
G00 Z2.00
G00 X0.0 Y0.0

